import { IAgent } from "./agents";
import { ChainName } from "./chains";
import { Activity } from "./activity";
import { IUnit, IUnitEmitData } from "./unit";
import { IDAOAPIDataV2 } from "./api";

/** Supported unit types */
export enum UnitType {
  /** VE-token early exit fees */
  PVP = "PVP",
  /** Decentralized finance protocol */
  DEFI_PROTOCOL = "DEFI_PROTOCOL",
  /** Maximum Extractable Value opportunities searcher and submitter. */
  MEV_SEARCHER = "MEV_SEARCHER",
  /** Software as a Service business */
  SAAS = "SAAS",
}

/** Unit status can be changed manually by DAO holders. Revenue of a unit matter. */
/** Unit status can be changed manually by DAO holders. Revenue of a unit matter. */
export enum UnitStatus {
  RESEARCH = "RESEARCH",
  BUILDING_PROTOTYPE = "BUILDING_PROTOTYPE",
  PROTOTYPE = "PROTOTYPE",
  BUILDING = "BUILDING",
  LIVE = "LIVE",
}

export interface IHostSettings {
  /** Create DAO price, ~USD */
  priceDao: number;
  /** Share of success funding rounds goes to core unit. 1_01 == 1.01%, 100_00 == 100% */
  fundingFee: number;
  minNameLength: number;
  maxNameLength: number;
  minSymbolLength: number;
  maxSymbolLength: number;
  minVePeriod: number;
  maxVePeriod: number;
  minPvPFee: number;
  maxPvPFee: number;
  minFunding: number;
  /** Min funding duration in days */
  minFundingDuration: number;
  /** Max funding duration in days */
  maxFundingDuration: number;
  /** Min allowed funding amount to raise in terms of exchange asset */
  minFundingRaise: number;
  /** Max allowed funding amount to raise in terms of exchange asset */
  maxFundingRaise: number;
  /** Min length of a vesting name  */
  minVestingNameLen: number;
  /** Max length of a vesting name */
  maxVestingNameLen: number;
  /** Min vesting duration in days*/
  minVestingDuration: number;
  /** Max vesting duration in days*/
  maxVestingDuration: number;

  /** Min allowed interval days between vesting.start and tge.claim */
  minCliff: number;
}

/**
 Represents a DAO running on Host.

 host-contracts: `IHost.DAOData`

 @version 0.7.0
 @alpha
 @interface
 */
export interface IDAOData {
  /** SEGMENT 1: ON-CHAIN on all chains where Host deployed */

  /**
   * Tradeable interchain ERC-20 token symbol.
   * Lowercased used as slug.
   * While token symbol is SYM then additional DAO tokens symbols are:
   * seedSYM, saleSYM, xSYM, SYM_DAO
   *
   * host-contracts: HostLib.OsStorage.usedSymbols
   */
  symbol: string;

  /** SEGMENT 2: ON-CHAIN on chains where DAO bridged */

  /** Unique ID of DAO */
  uid?: string;

  /** Name of the DAO, used in token names. Without DAO word. */
  name: string;

  /**
   DAO lifecycle phase.
   Changes permissionless when next phase start timestamp reached.
   */
  phase: LifecyclePhase;

  /**
   Deployed smart-contracts.
   host-contracts: deployments of current instance chain only.
   */
  deployments: IDAODeployments;

  /**
   Settings of DAO for chains.
   host-contracts: settings of current instance chain only. This is the only place to save settings of DAO for chains.
   */
  chainSettings: IDAOChainSettings;

  /** IDs of Units running on current chain */
  unitIds?: string[];

  /** Revenue generated by a Unit */
  unitRevenue?: { [asset: `0x${string}`]: bigint }[];

  /** On-chain DAO parameters for tokenomics and revenue sharing */
  params: IDAOParameters;

  /** SEGMENT 3: ON-CHAIN on initial chain of DAO */

  /** Where initial deployment became */
  initialChain: ChainName;

  /** Community socials. Update by `Host.updateSocials` */
  socials: string[];

  /** Activities of the organization. */
  activity: Activity[];

  /** Images of tokens. Absolute or relative from stabilitydao/.github repo /os/ folder.  */
  images: IDAOImages;

  /** Revenue generating units owned by the organization. */
  units: IUnit[];

  /** Fundraising */
  funding: IFunding[];

  /** Vesting allocations  */
  vesting: IVesting[];

  /** Settings of DAO Governance */
  governanceSettings: IGovernanceSettings;

  /** Deployer of a DAO have power only at DRAFT phase. */
  deployer: string;

  salts: {
    [chainId: string]: {
      [index in ContractIndices]?: string;
    };
  };

  /** DAO custom metadata stored off-chain. */
  metaDataLocation?: string; // "local","https://..."

  /** SEGMENT 4: OFF-CHAIN emitted data */

  unitEmitData: IUnitEmitData[];

  /** SEGMENT 5: OFF-CHAIN data on custom location */

  /** Storage for Agents data. */
  metaData?: IDAOMetaData;

  /** SEGMENT 6: API data of DAO provided by HOST */

  /** Hot data updates each minute */
  api?: IDAOAPIDataV2;
}

/** Storage for Agents data. */
export interface IDAOMetaData {
  /** Operating agents managed by the organization. */
  agents?: IAgent[];
}

/** Images of tokens. Absolute or relative from stabilitydao/.github repo /os/ folder.  */
export interface IDAOImages {
  seedToken?: string;
  tgeToken?: string;
  token?: string;
  xToken?: string;
  daoToken?: string;
}

/**
 Lifecycle phase represents DAO tokenomics stage.
 */
export enum LifecyclePhase {
  /** Created */
  DRAFT = "DRAFT",

  /**
   * DAO ready to attract initial community
   */
  INCEPTION = "INCEPTION",

  /**
   Initial funding. DAO project passed requirements.
   Since SEED started a DAO become real DAO:
   - noncustodial
   - tokenized share holdings
   - collective management via voting
   */
  SEED = "SEED",

  /** Seed was not success. Raised funds sent back to seeders. */
  SEED_FAILED = "SEED_FAILED",

  /** Using SEED funds to launch MVP / Unit generating */
  DEVELOPMENT = "DEVELOPMENT",

  /** TGE is funding event for token liquidity and DAO developments (optionally) */
  TGE = "TGE",

  /** Delay before any vesting allocation started */
  LIVE_CLIFF = "LIVE_CLIFF",

  /** Vesting period active */
  LIVE_VESTING = "LIVE_VESTING",

  /** Vesting ended - token fully distributed */
  LIVE = "LIVE",
}

/**
 Parameters of VE-tokenomics and revenue sharing.
 @interface
 */
export interface IDAOParameters {
  /** Vested Escrow period, days. */
  vePeriod: number;
  /** Instant exit fee, percent */
  pvpFee: number;
  /** Minimal power (min stake amount) to be a holder of DAO */
  minPower?: number;
  /** Share of total DAO revenue going to accidents compensations, percent */
  recoveryShare?: number;
  /** Total supply of DAO token. This value can be changed before start of TGE*/
  totalSupply: number;
}

/**
 Settings of DAO for chains.
 host-contracts: settings of current instance chain only. This is the only place to save settings of DAO for chains.
 */
export interface IDAOChainSettings {
  [chainId: string]: {
    /** Revenue percent goes to xToken buy-backs */
    bbRate: number;
    /** GitHub organization (from socials) EVM multisig address */
    multisig?: `0x${string}`;
  };
}

export interface IGovernanceSettings {
  /** Minimal total voting power (self and delegated) need to create a proposal */
  proposalThreshold?: number;
  /** Bribe share for Tokenomics Transactions (vested funds spending), percent */
  ttBribe?: number;
}

export interface IFunding {
  type: FundingType;
  start: number;
  end: number;
  minRaise: number;
  maxRaise: number;
  raised: number;

  /** Date of DAO launching (after TGE finishing, DAO token is deployed, etc) */
  claim?: number;
}

export enum FundingType {
  SEED = "SEED",
  TGE = "TGE",
}

/**
 Vesting allocation data
 @interface
 */
export interface IVesting {
  /** Short name of vesting allocation */
  name: string;
  /** How must be spent */
  description?: string;
  /** Vesting supply. 10 == 10e18 TOKEN */
  allocation: number;
  /** Start timestamp */
  start: number;
  /** End timestamp */
  end: number;
  address?: `0x${string}`;
}

/// @notice Indices of all contracts that can be deployed by a DAO. The indices are used to pre-set salts
export enum ContractIndices {
  NOT_USED_0,
  SEED_TOKEN_1,
  TGE_TOKEN_2,
  TOKEN_3,
  X_TOKEN_4,
  DAO_TOKEN_5,
  STAKING_6,
  RECOVERY_7,
  TOKEN_BRIDGE_8,
  X_TOKEN_BRIDGE_9,
  DAO_TOKEN_BRIDGE_10,
  VESTING_1_11,
  VESTING_2_12,
  VESTING_3_13,
  VESTING_4_14,
  VESTING_5_15,
  VESTING_6_16,
  VESTING_7_17,
  VESTING_8_18,
  VESTING_9_19,
  VESTING_10_20,
  REVENUE_ROUTER_21,

  // add new indices here if necessary

  COUNT_CONTRACT_INDICES,
}

export interface IContractIndex {
  name: string;
  description?: string;
}

/**
 Deployments of running DAO on blockchains.

 @interface
 */
export interface IDAODeployments {
  [chainId: string]: {
    [index in ContractIndices]?: `0x${string}`;
  };
}

export const HOST_DESCRIPTION = "Home for DAOs";
export const DAO_FEATURES: string[] = [
  "True DAO: only holders owns, manage and earn whole value",
  "Inter-chain setup with bridging",
  "Decentralized fundraising",
  "Self-developing via Builder activity",
  "Tokenomics constructor",
  "Proper token launch flow to get cg/cmc and wallets listings",
  "Deterministic managed contract addresses",
];
export const STATIC_BASE_URL: `https://${string}` =
  "https://raw.githubusercontent.com/stabilitydao/.github/main";
