name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - run: yarn build
      # We use npm here because it natively handles the OIDC token exchange
      - run: npm publish --provenance --access public
        env:
         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # NOT REQUIRED with OIDC, leave this out!
      #- run: yarn publish --access public
      #  env:
      #    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
